[rules]
if_same_then_else = 'allow'
mixed_table = 'allow'
shadowing = 'allow'
unscoped_variables = 'allow'
undefined_variable = 'allow'
multiple_statements = 'allow'
incorrect_standard_library_use = 'allow'
