$env.config.datetime_format.normal = '%y.%m.%d %H:%M:%S %A'
$env.config.datetime_format.table = null
$env.config.float_precision = 3
$env.config.rm.always_trash = true
$env.config.table.missing_value_symbol = '❌'
$env.config.table.padding.left = 0
$env.config.table.padding.right = 0
$env.config.table.show_empty = true # “no values” when list or table is empty
$env.config.table.trim.wrapping_try_keep_words = false
$env.config.table.mode = 'single'
