AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.5

Layout/DefEndAlignment:
  Enabled: false

Layout/LineLength:
  Max: 111

Layout/ElseAlignment:
  Severity: refactor

Layout/EmptyLineBetweenDefs:
  Severity: refactor

Layout/EmptyLines:
  Severity: refactor

Layout/EmptyLinesAroundAttributeAccessor:
  Severity: refactor

Layout/EmptyLinesAroundClassBody:
  Severity: refactor

Layout/EndAlignment:
  Severity: refactor
  
Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 3

Layout/IndentationWidth:
  Width: 1
  Enabled: true
  Severity: refactor

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceAroundOperators:
  Severity: refactor

Layout/SpaceInsideArrayLiteralBrackets:
  Severity: refactor

Layout/SpaceInsideBlockBraces:
  Severity: refactor

Layout/TrailingEmptyLines:
  Severity: refactor

Layout/TrailingWhitespace:
  Severity: refactor
 
Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/DuplicateMethods:
  Severity: refactor

Lint/EmptyClass:
  Enabled: false

Lint/UselessAssignment:
  Severity: refactor

Naming/FileName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodDefinition:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyBlockParameter:
  Severity: refactor

Style/EmptyMethod:
  Enabled: false
  # Severity: refactor
  # AutoCorrect: always
  # SafeAutocorrect: false

Style/GlobalVars:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/RedundantInitialize:
  Enabled: false

Style/SingleLineDoEndBlock:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
  # Severity: refactor

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: true
  AutoCorrect: always

Style/VariableInterpolation:
  Severity: refactor
