Layout/LineLength:
  Max: 111

Layout/EmptyLineBetweenDefs:
  Severity: refactor

Layout/EmptyLines:
  Severity: refactor

Layout/IndentationStyle:
  EnforcedStyle: tabs
  IndentationWidth: 3

Layout/IndentationWidth:
  Width: 1
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Severity: refactor

Layout/SpaceInsideBlockBraces:
  Severity: refactor

Layout/TrailingEmptyLines:
  Severity: refactor

Layout/TrailingWhitespace:
  Severity: refactor
 
Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UselessAssignment:
  Severity: refactor

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodDefinition:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Severity: refactor
  # AutoCorrect: always
  # SafeAutocorrect: false

Style/GlobalVars:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Severity: refactor

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/VariableInterpolation:
  Severity: refactor
