# [[sort on]]
# grace_period = '15ms' # delay after file event, after which to do the bacon action. can be set to 'none'
# help_line = false
# on_change_strategy = 'kill_then_restart'
# on_change_strategy = 'wait_then_restart'
# reverse = true
# summary = true
# wrap = false
# show_changes_count = false
default_job = 'clippy'
# [[sort off]]

[keybindings]
# [[sort on]]
'?' = 'no-op'
F1 = 'help'
F5 = 'no-op'
a = 'toggle-summary'
alt-space = 'quit'
c = 'job:clippy'
ctrl-c = 'no-op'
ctrl-q = 'no-op'
ctrl-r = 'refresh'
end = 'scroll-to-bottom'
f = 'toggle-pause'
h = 'no-op'
home = 'scroll-to-top'
j = 'scroll-lines(1)'
k = 'scroll-lines(-1)'
n = 'next-match'
p = 'no-op'
pagedown = 'scroll-pages(0.5)'
pageup = 'scroll-pages(-0.5)'
r = 'job:run'
s = 'copy-unstyled-output'
shift-n = 'previous-match'
space = 'no-op'
t = 'job:test'
# [[sort off]]
