# [[sort on]]
# help_line = false
default_job = 'clippy'
on_change_strategy = 'kill_then_restart'
# [[sort off]]

[exports.locations]
auto = true
exporter = 'locations'
path = '.bacon-locations'
line_format = '{path}:{line}:{column}'

[jobs.fix]
command = [
  'cargo',
  'clippy',
  '--fix',
  '--workspace',
  '--allow-dirty',
  '--allow-staged',
]
on_success = 'back'

[jobs.neru]
command = [ 'neru', 'launch' ]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
scroll_anchor = "auto"
watch = [ 'neru.toml' ]

[skin]
# [[sort on]]
change_badge_fg = { r = 31, g = 31, b = 31 }
command_error_badge_fg = { r = 31, g = 31, b = 31 }
computing_bg = { r = 228, g = 150, b = 65 }
computing_fg = { r = 31, g = 31, b = 31 }
dismissed_badge_fg = { r = 31, g = 31, b = 31 }
errors_badge_fg = { r = 31, g = 31, b = 31 }
found_fg = { r = 228, g = 150, b = 65 }
found_selected_bg = { r = 228, g = 150, b = 65 }
job_label_badge_bg = { r = 228, g = 150, b = 65 }
job_label_badge_fg = { r = 31, g = 31, b = 31 }
key_fg = { r = 228, g = 150, b = 65 }
menu_bg = { r = 31, g = 31, b = 31 }
menu_border = { r = 31, g = 31, b = 31 }
menu_item_bg = { r = 31, g = 31, b = 31 }
menu_item_fg = { r = 212, g = 190, b = 152 }
menu_item_selected_bg = { r = 95, g = 71, b = 45 }
menu_item_selected_fg = { r = 212, g = 190, b = 152 }
project_name_badge_bg = { r = 181, g = 140, b = 198 }
project_name_badge_fg = { r = 31, g = 31, b = 31 }
search_input_prefix_fg = { r = 228, g = 150, b = 65 }
search_summary_fg = { r = 212, g = 190, b = 152 }
status_bg = { r = 40, g = 40, b = 40 }
status_fg = { r = 212, g = 190, b = 152 }
status_key_fg = { r = 228, g = 150, b = 65 }
test_fails_badge_bg = { r = 234, g = 105, b = 98 }
test_fails_badge_fg = { r = 31, g = 31, b = 31 }
test_pass_badge_fg = { r = 169, g = 182, b = 101 }
warnings_badge_fg = { r = 31, g = 31, b = 31 }
# [[sort off]]

[keybindings]
# [[sort on]]
'?' = 'no-op'
0 = 'show-item(10)'
1 = 'show-item(1)'
2 = 'show-item(2)'
3 = 'show-item(3)'
4 = 'show-item(4)'
5 = 'show-item(5)'
6 = 'show-item(6)'
7 = 'show-item(7)'
8 = 'show-item(8)'
9 = 'show-item(9)'
F1 = 'help'
F5 = 'no-op'
a = 'no-op'
alt-i = 'no-op'
alt-space = 'quit'
alt-t = 'no-op'
alt-u = 'no-op'
alt-w = 'no-op'
backtab = 'no-op'
c = 'job:clippy'
ctrl-c = 'job:pedantic'
ctrl-d = 'no-op'
ctrl-end = 'scroll-to-bottom'
ctrl-home = 'scroll-to-top'
ctrl-j = 'open-jobs-menu'
ctrl-q = 'no-op'
ctrl-r = 'refresh'
down = 'scroll-lines(1)'
end = 'no-op'
esc = 'back'
f = 'toggle-pause'
h = 'no-op'
home = 'no-op'
j = 'undismiss-all'
k = 'dismiss-top-item'
l = 'job:default'
n = 'next-match'
p = 'no-op'
pagedown = 'scroll-pages(0.5)'
pageup = 'scroll-pages(-0.5)'
q = 'no-op'
r = 'job:run'
s = 'copy-unstyled-output'
shift-c = 'job:clippy-all'
shift-d = 'job:doc'
shift-j = 'open-undismiss-menu'
shift-k = 'dismiss-top'
shift-n = 'previous-match'
shift-r = 'toggle-raw-output'
shift-t = 'scope-to-failures'
shift-tab = 'no-op'
shift-w = 'toggle-wrap'
space = 'no-op'
t = 'job:test'
tab = 'no-op'
u = 'toggle-summary'
up = 'scroll-lines(-1)'
w = 'no-op'
x = 'job:fix'
# [[sort off]]
