[flags]
cpu_left_legend = true
hide_table_gap = true
process_memory_as_value = true
show_table_scroll_position = true
process_command = true
memory_legend = "top-left"
network_legend = "top-left"

[cpu]
default = "average"

[disk]
columns = [
  "Mount",
  "Disk",
  "Total",
  "Used",
  "Free",
  "Used%",
  "R/s",
  "W/s",
]

[processes]
columns = [
  "pid",
  "name",
  "cpu%",
  "mem%",
  "gmem%",
  "gpu%",
  "time",
  "user",
  "read",
  "write",
  # "state",
  # "tread",
  # "twrite",
]

[styles]
tables = { headers = { color = "#e491b2", bold = true } }

[styles.cpu]
all_entry_color = "#78bf84"
avg_entry_color = "#e491b2"
cpu_core_colors = [ "#ea6962", "#e49641", "#d3ad5c", "#a9b665" ]

[styles.memory]
ram_color = "#e491b2"
gpu_colors = [ "#78bf84" ]
# swap_color = "#7daea3"

[styles.network]
rx_color = "#e491b2"
tx_color = "#78bf84"

[styles.widgets]
border_color = "#b58cc6"
widget_title = "#b58cc6"
selected_border_color = "#e491b2"
selected_text = { color = "white", bg_color = "#593d48" }
disabled_text = { color = "#928374" }

[[row]]
ratio = 25
[[row.child]]
type = "mem"
[[row.child]]
type = "net"
[[row]]
ratio = 45
[[row.child]]
type = "cpu"
[[row.child]]
[[row.child.child]]
ratio = 5
type = "temp"
[[row.child.child]]
ratio = 3
type = "disk"
[[row]]
ratio = 30
[[row.child]]
type = "proc"
default = true
