[alias]
a = 'add'
br = 'build --release'
c = 'clippy'
cc = 'clippy --fix --workspace --allow-dirty --allow-staged'
d = 'doc --no-deps --workspace'
do = 'doc --open --no-deps --workspace'
f = 'fmt'
i = 'info'
q = 'run -q'
qr = 'run -q --release'
rr = 'run --release'
s = 'search'
seek = 'seek --fps 100'

[env]
RUST_LOG = 'trace'

[build]
jobs = -1
rustc-wrapper = 'sccache'
rustflags = [ '-C', 'target-cpu=native' ]
# rustdocflags = [  ]

[unstable]
mtime-on-use = true # update modification time of artifacts whenever you use them, so that you can reliably consider old artifacts to be *useless* ones

[target.'cfg(target_os = "linux")']
rustflags = [ '-C', 'link-arg=-fuse-ld=mold' ] # faster linker
