# /etc/xdg/fuzzel/fuzzel.ini

[main]
# [[sort on]]
font=Google Sans Code:size=18
horizontal-pad=12
icon-theme=Papirus
image-size-ratio=0.2
inner-pad=7
layer=overlay
line-height=26
lines=8
match-mode=fuzzy
minimal-lines=yes
prompt=""
tabs=1
terminal=footclient
vertical-pad=9
width=50
# [[sort off]]

[colors]
# [[sort on]]
background=1f1e1ee6
border=ffd75fff
input=d4be98ff
match=ffd75fff
placeholder=928374ff
prompt=d4be98ff
selection-match=ffd75fff
selection-text=d4be98ff
selection=68622cbb
text=d4be98ff
# [[sort off]]

[border]
width=2
radius=20

[key-bindings]
# [[sort on]]
cursor-end=End Control+e
cursor-home=Home Control+a
custom-1=Control+Return
custom-2=Control+Shift+Return
first=Control+Home
insert-selected=Shift+Right
last=Control+End
next-with-wrap=none
next=Down Control+n
prev-with-wrap=none
prev=Up Control+p
