[user]
name = 'Axlefublr'
email = '101342105+Axlefublr@users.noreply.github.com'

[ui]
pager = ':builtin'
paginate = "auto"
diff-editor = ':builtin'
default-command = 'status'
graph.style = 'square'
log-word-wrap = true

[colors]
'diff token' = {}

[templates]
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: changes:\n", "",
    indent("JJ:    ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[template-aliases]
'format_short_id(id)' = 'id.shortest(8)'
'format_short_signature(signature)' = 'signature.name()'

[diff.color-words]
context = 3
