format = """
[╭─](yellow)$shlvl\
$username\
$hostname\
$localip\
$singularity
[│](yellow) $directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
[╰─](yellow)$character"""

add_newline = false
palette = 'pinkie'

[palettes.pinkie]
pink        = '#FFAFD7'
purple      = '#AF87FF'
grey        = '#878787'
yellow      = '#FFD75F'
green       = '#87FF5F'
cyan        = '#00D7FF'
red         = '#FF005F'
orange      = '#FF8700'
redder_pink = '#FF8787'

[character]
format = '$symbol '
success_symbol = '[>](yellow)'
error_symbol = '[>](redder_pink)'
vimcmd_symbol = '[\$](yellow)'