[keys.viewer]
# [[sort on]]
0 = none
Alt+ScrollDown = none
Alt+ScrollUp = none
Alt+s = none
BackSpace = none
Ctrl+ScrollDown = none
Ctrl+ScrollUp = none
Down = step_down 10
Equal = none
Escape = exit
F1 = help
Left = step_left 10
Minus = zoom -10
MouseExtra = none
MouseSide = none
Next = none
Plus = zoom +10
Prior = none
Return = mode
Right = step_right 10
ScrollDown = none
ScrollDown = zoom -10
ScrollLeft = none
ScrollRight = none
ScrollUp = none
ScrollUp = zoom +10
Shift+Delete = none
Shift+Plus = zoom +10
Shift+ScrollDown = none
Shift+ScrollUp = none
Shift+d = none
Shift+o = none
Shift+r = none
Shift+s = none
Shift+w = none
Shift+z = none
Space = none
Up = step_up 10
h = step_left 10
j = step_down 10
k = step_up 10
l = step_right 10
q = none
w = none
# [[sort off]]

[keys.gallery]
# [[sort on]]
Ctrl+ScrollDown = thumb -20
Ctrl+ScrollUp = thumb +20
Down = step_down
Equal = thumb +20
F1 = help
Left = step_left
Minus = thumb -20
MouseLeft = none
Next = none
Prior = none
Return = mode
Right = step_right
ScrollDown = none
ScrollLeft = none
ScrollRight = none
ScrollUp = none
Shift+Delete = none
Shift+Plus = thumb +20
Up = step_up
a = none
f = none
h = step_left
j = step_down
k = step_up
l = step_right
q = none
r = none
# [[sort off]]
