default_tool = 'arrow'
remember_last_tool = false
stroke_size = 6.0
default_color = '#e84046'
feedback_duration_ms = 500
# [[sort on]]
tools.arrow.roundness = 1.0
tools.line.roundness = 1.0
tools.rectangle.roundness = 0.0
tools.text.background = true
tools.text.roundness = 0.4
tools.text.size = 30.0
tools.text.size_range.step = 1.0
# [[sort off]]
palette = [
  '#e84046', # red
  # '#ffafd7', # pink
  '#ec8948', # orange
  '#eed049', # yellow
  '#3ed73c', # green
  '#0283fc', # blue
  '#7c57eb', # purple
  '#ffffff',
  '#0f0f0f',
]
