default_tool = 'arrow'
remember_last_tool = true
stroke_width = 6.0
default_color = '#e84046'
feedback_duration_ms = 500
# palette = [
#   "#e84046", # red
#   "#ec8948", # orange
#   "#eed049", # yellow
#   "#3ed73c", # green
#   "#0283fc", # blue
#   "#7c57eb", # purple
#   "#ffffff",
#   "#000000",
# ]
