'$schema' = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
# [[sort on]]
ratio = [ 0, 1, 1 ]
scrolloff = 255
show_hidden = false
sort_by = "natural"
sort_sensitive = true
sort_translit = true
# [[sort off]]

[preview]
tab_size = 3
wrap = "yes"
max_width = 1000

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "Edit", block = true },
]
extract = [
  { run = 'ouch decompress "$@"', desc = "Extract here" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
]

[open]
prepend_rules = [
  { mime = "image/svg+xml", use = [ "open", "edit", "reveal" ] },
]

[tasks]
suppress_preload = true

[input]
# [[sort on]]
cd_origin = "top-center"
create_origin = "top-center"
filter_origin = "top-center"
find_origin = "top-center"
rename_offset = [ 0, 2, 50, 3 ]
rename_origin = "top-center"
search_origin = "top-center"
shell_origin = "top-center"
# [[sort off]]

[pick]
open_origin = "top-center"
