[global]
cr = 'crystal'
dt = '%sh{date +%%y.%%m.%%d}'
exp1 = '%{cursor_line}'                       # ✅
exp2 = '%{cursor_column}'                     # ✅
exp3 = '%{buffer_name}'                       # ✅
exp4 = '%{line_ending}'                       # ✅
exp5 = '%{working_directory}'                 # ✅
exp6 = '%{workspace_directory}'               # ✅
exp7 = '%{language}'                          # ✅
exp8 = '%{selection}'                         # ✅ but it doesn't seem useful
exp9 = '%{selection_line_start}'              # ✅
exp10 = '%{selection_line_end}'               # ✅
exp11 = '%{relative_path}'                    # ✅
exp12 = '%{buffer_parent}'                    # ✅
exp13 = '%{buffer_stem}'                      # ✅
exp14 = '%{selection_line_start_indentation}' # ✅, its problematicness is unrelated to how it interacts with snippets

[bash]
'#' = '#!/usr/bin/env dash'

[crystal]
do = '''
do █
end'''
dod = '''
do |█|
end'''
fn = '''
def █
end'''

[css]
i = '!important'
dn = 'display: none█;'
shadow = '''
box-shadow:
	-█px -█px ■ #000000,
	 0   -█px ■ #000000,
	 █px -█px ■ #000000,
	-█px  0   ■ #000000,
	 █px  0   ■ #000000,
	-█px  █px ■ #000000,
	 0    █px ■ #000000,
	 █px  █px ■ #000000;'''

[fish]
# [[sort on]]
'#' = '#!/usr/bin/env fish'
alias = "alias --save █ '■' >/dev/null"
b = '&>/dev/null'
e = '2>/dev/null'
o = '>/dev/null'
set = 'set -l'
# [[sort off]]
fn = '''
function █
end
funcsave █ >/dev/null'''

[html]
o = '<o>█</o>'
cd = '<cd>█</cd>'

[markdown]
d = '<kbd>█</kbd>'
"+++" = """
+++
title = '█'
date = '2026-■'
draft = true
+++
"""
j = '''
```█
```'''
jc = '''
```crystal█
```'''

[nbcl]
the = """
Window 'example' {
	stacking = 'overlay'
	namespace = 'eww'
	passinput = true
	geometry = {
		width  = '█px'
		height = '█px'
		anchor = 'center'
	}
	Box {
	}
}"""

[nu]
'#' = '#!/usr/bin/env -S nu -n --no-std-lib'

[python]
'#' = '#!/usr/bin/env python'

[ruby]
'#' = '''
#!/usr/bin/env ruby
# frozen_string_literal: true'''

[rust]
in = 'into()'
fr = 'from()'
toow = 'to_owned()'
stf = 'String::from("█")'
dbg = 'std::process::Command::new("dbglog.sh").arg(format!("{█:?}")).status().unwrap();'
ntf = 'std::process::Command::new("ntf").arg(format!("{█:?}")).status().unwrap();'
'{}' = '''
{
    █
};'''
test = '''
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn █() {
    }
}
'''
