[global]
# [[sort on]]
csl = '%{cursor_line}'
dT = '%sh{date +%%Y-%%m-%%d}'
dt = '%sh{date +%%y.%%m.%%d}'
tm = '%sh{date +%%H:%%M}'
# [[sort off]]

exp5 = '%{working_directory}' # cwd ❌(d → d↓j is yuck)
exp7 = '%{language}'          # la
exp11 = '%{relative_path}'
exp12 = '%{buffer_parent}'
exp13 = '%{buffer_stem}'
exp3 = '%{buffer_name}'
exp1 = '%{full_path}'

[bash]
'#' = '#!/usr/bin/env dash'

[crystal]
do = '''
do █
end'''
dod = '''
do |█|
end'''
fn = '''
def █
end'''

[css]
i = '!important'
dn = 'display: none█;'
shadow = '''
box-shadow:
	-█px -█px ■ #000000,
	 0   -█px ■ #000000,
	 █px -█px ■ #000000,
	-█px  0   ■ #000000,
	 █px  0   ■ #000000,
	-█px  █px ■ #000000,
	 0    █px ■ #000000,
	 █px  █px ■ #000000;'''

[fish]
# [[sort on]]
'#' = '#!/usr/bin/env fish'
alias = "alias --save █ '■' >/dev/null"
b = '&>/dev/null'
e = '2>/dev/null'
o = '>/dev/null'
set = 'set -l'
# [[sort off]]
fn = '''
function █
end
funcsave █ >/dev/null'''

[html]
o = '<o>█</o>'
cd = '<cd>█</cd>'

[markdown]
r = 'crystal'
d = '<kbd>█</kbd>'
"+++" = """
+++
title = '█'
date = '2026-■'
draft = true
+++
"""
j = '''
```█
```'''
jc = '''
```crystal█
```'''

[nbcl]
the = """
Window 'example' {
	stacking = 'overlay'
	namespace = 'eww'
	passinput = true
	geometry = {
		width  = '█px'
		height = '█px'
		anchor = 'center'
	}
	Box {
	}
}"""

[nu]
'#' = '#!/usr/bin/env -S nu -n --no-std-lib'

[python]
'#' = '#!/usr/bin/env python'

[ruby]
'#' = '''
#!/usr/bin/env ruby
# frozen_string_literal: true'''

[rust]
in = 'into()'
fr = 'from()'
toow = 'to_owned()'
stf = 'String::from("█")'
dbg = 'std::process::Command::new("dbglog.sh").arg(format!("{█:?}")).status().unwrap();'
ntf = 'std::process::Command::new("ntf").arg(format!("{█:?}")).status().unwrap();'
'{}' = '''
{
    █
};'''
test = '''
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn █() {
    }
}
'''
