bind 'ma' 'z "$(harp get cd_harps a --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mb' 'z "$(harp get cd_harps b --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mc' 'z "$(harp get cd_harps c --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'md' 'z "$(harp get cd_harps d --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'me' 'z "$(harp get cd_harps e --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mf' 'z "$(harp get cd_harps f --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mg' 'z "$(harp get cd_harps g --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mh' 'z "$(harp get cd_harps h --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mi' 'z "$(harp get cd_harps i --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mj' 'z "$(harp get cd_harps j --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mk' 'z "$(harp get cd_harps k --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'ml' 'z "$(harp get cd_harps l --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mm' 'z "$(harp get cd_harps m --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mn' 'z "$(harp get cd_harps n --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mo' 'z "$(harp get cd_harps o --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mp' 'z "$(harp get cd_harps p --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mq' 'z "$(harp get cd_harps q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mr' 'z "$(harp get cd_harps r --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'ms' 'z "$(harp get cd_harps s --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mt' 'z "$(harp get cd_harps t --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mu' 'z "$(harp get cd_harps u --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mv' 'z "$(harp get cd_harps v --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mw' 'z "$(harp get cd_harps w --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mx' 'z "$(harp get cd_harps x --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'my' 'z "$(harp get cd_harps y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mz' 'z "$(harp get cd_harps z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind 'mA' 'z "$(harp get cd_harps A --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mB' 'z "$(harp get cd_harps B --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mC' 'z "$(harp get cd_harps C --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mD' 'z "$(harp get cd_harps D --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mE' 'z "$(harp get cd_harps E --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mF' 'z "$(harp get cd_harps F --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mG' 'z "$(harp get cd_harps G --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mH' 'z "$(harp get cd_harps H --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mI' 'z "$(harp get cd_harps I --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mJ' 'z "$(harp get cd_harps J --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mK' 'z "$(harp get cd_harps K --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mL' 'z "$(harp get cd_harps L --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mM' 'z "$(harp get cd_harps M --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mN' 'z "$(harp get cd_harps N --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mO' 'z "$(harp get cd_harps O --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mP' 'z "$(harp get cd_harps P --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mQ' 'z "$(harp get cd_harps Q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mR' 'z "$(harp get cd_harps R --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mS' 'z "$(harp get cd_harps S --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mT' 'z "$(harp get cd_harps T --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mU' 'z "$(harp get cd_harps U --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mV' 'z "$(harp get cd_harps V --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mW' 'z "$(harp get cd_harps W --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mX' 'z "$(harp get cd_harps X --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mY' 'z "$(harp get cd_harps Y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'mZ' 'z "$(harp get cd_harps Z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind 'm1' 'z "$(harp get cd_harps 1 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm2' 'z "$(harp get cd_harps 2 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm3' 'z "$(harp get cd_harps 3 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm4' 'z "$(harp get cd_harps 4 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm5' 'z "$(harp get cd_harps 5 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm6' 'z "$(harp get cd_harps 6 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm7' 'z "$(harp get cd_harps 7 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm8' 'z "$(harp get cd_harps 8 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm9' 'z "$(harp get cd_harps 9 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind 'm0' 'z "$(harp get cd_harps 0 --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind 'Ma' 'harp update cd_harps a --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark a ; commandline -f repaint'
bind 'Mb' 'harp update cd_harps b --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark b ; commandline -f repaint'
bind 'Mc' 'harp update cd_harps c --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark c ; commandline -f repaint'
bind 'Md' 'harp update cd_harps d --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark d ; commandline -f repaint'
bind 'Me' 'harp update cd_harps e --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark e ; commandline -f repaint'
bind 'Mf' 'harp update cd_harps f --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark f ; commandline -f repaint'
bind 'Mg' 'harp update cd_harps g --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark g ; commandline -f repaint'
bind 'Mh' 'harp update cd_harps h --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark h ; commandline -f repaint'
bind 'Mi' 'harp update cd_harps i --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark i ; commandline -f repaint'
bind 'Mj' 'harp update cd_harps j --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark j ; commandline -f repaint'
bind 'Mk' 'harp update cd_harps k --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark k ; commandline -f repaint'
bind 'Ml' 'harp update cd_harps l --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark l ; commandline -f repaint'
bind 'Mm' 'harp update cd_harps m --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark m ; commandline -f repaint'
bind 'Mn' 'harp update cd_harps n --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark n ; commandline -f repaint'
bind 'Mo' 'harp update cd_harps o --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark o ; commandline -f repaint'
bind 'Mp' 'harp update cd_harps p --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark p ; commandline -f repaint'
bind 'Mq' 'harp update cd_harps q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark q ; commandline -f repaint'
bind 'Mr' 'harp update cd_harps r --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark r ; commandline -f repaint'
bind 'Ms' 'harp update cd_harps s --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark s ; commandline -f repaint'
bind 'Mt' 'harp update cd_harps t --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark t ; commandline -f repaint'
bind 'Mu' 'harp update cd_harps u --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark u ; commandline -f repaint'
bind 'Mv' 'harp update cd_harps v --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark v ; commandline -f repaint'
bind 'Mw' 'harp update cd_harps w --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark w ; commandline -f repaint'
bind 'Mx' 'harp update cd_harps x --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark x ; commandline -f repaint'
bind 'My' 'harp update cd_harps y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark y ; commandline -f repaint'
bind 'Mz' 'harp update cd_harps z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark z ; commandline -f repaint'

bind 'MA' 'harp update cd_harps A --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark A ; commandline -f repaint'
bind 'MB' 'harp update cd_harps B --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark B ; commandline -f repaint'
bind 'MC' 'harp update cd_harps C --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark C ; commandline -f repaint'
bind 'MD' 'harp update cd_harps D --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark D ; commandline -f repaint'
bind 'ME' 'harp update cd_harps E --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark E ; commandline -f repaint'
bind 'MF' 'harp update cd_harps F --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark F ; commandline -f repaint'
bind 'MG' 'harp update cd_harps G --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark G ; commandline -f repaint'
bind 'MH' 'harp update cd_harps H --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark H ; commandline -f repaint'
bind 'MI' 'harp update cd_harps I --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark I ; commandline -f repaint'
bind 'MJ' 'harp update cd_harps J --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark J ; commandline -f repaint'
bind 'MK' 'harp update cd_harps K --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark K ; commandline -f repaint'
bind 'ML' 'harp update cd_harps L --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark L ; commandline -f repaint'
bind 'MM' 'harp update cd_harps M --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark M ; commandline -f repaint'
bind 'MN' 'harp update cd_harps N --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark N ; commandline -f repaint'
bind 'MO' 'harp update cd_harps O --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark O ; commandline -f repaint'
bind 'MP' 'harp update cd_harps P --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark P ; commandline -f repaint'
bind 'MQ' 'harp update cd_harps Q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Q ; commandline -f repaint'
bind 'MR' 'harp update cd_harps R --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark R ; commandline -f repaint'
bind 'MS' 'harp update cd_harps S --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark S ; commandline -f repaint'
bind 'MT' 'harp update cd_harps T --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark T ; commandline -f repaint'
bind 'MU' 'harp update cd_harps U --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark U ; commandline -f repaint'
bind 'MV' 'harp update cd_harps V --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark V ; commandline -f repaint'
bind 'MW' 'harp update cd_harps W --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark W ; commandline -f repaint'
bind 'MX' 'harp update cd_harps X --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark X ; commandline -f repaint'
bind 'MY' 'harp update cd_harps Y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Y ; commandline -f repaint'
bind 'MZ' 'harp update cd_harps Z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Z ; commandline -f repaint'

bind 'M1' 'harp update cd_harps 1 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 1 ; commandline -f repaint'
bind 'M2' 'harp update cd_harps 2 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 2 ; commandline -f repaint'
bind 'M3' 'harp update cd_harps 3 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 3 ; commandline -f repaint'
bind 'M4' 'harp update cd_harps 4 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 4 ; commandline -f repaint'
bind 'M5' 'harp update cd_harps 5 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 5 ; commandline -f repaint'
bind 'M6' 'harp update cd_harps 6 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 6 ; commandline -f repaint'
bind 'M7' 'harp update cd_harps 7 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 7 ; commandline -f repaint'
bind 'M8' 'harp update cd_harps 8 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 8 ; commandline -f repaint'
bind 'M9' 'harp update cd_harps 9 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 9 ; commandline -f repaint'
bind 'M0' 'harp update cd_harps 0 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 0 ; commandline -f repaint'
