bind ',sda' 'z "$(harp get cd_harps a --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdb' 'z "$(harp get cd_harps b --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdc' 'z "$(harp get cd_harps c --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdd' 'z "$(harp get cd_harps d --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sde' 'z "$(harp get cd_harps e --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdf' 'z "$(harp get cd_harps f --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdg' 'z "$(harp get cd_harps g --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdh' 'z "$(harp get cd_harps h --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdi' 'z "$(harp get cd_harps i --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdj' 'z "$(harp get cd_harps j --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdk' 'z "$(harp get cd_harps k --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdl' 'z "$(harp get cd_harps l --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdm' 'z "$(harp get cd_harps m --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdn' 'z "$(harp get cd_harps n --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdo' 'z "$(harp get cd_harps o --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdp' 'z "$(harp get cd_harps p --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdq' 'z "$(harp get cd_harps q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdr' 'z "$(harp get cd_harps r --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sds' 'z "$(harp get cd_harps s --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdt' 'z "$(harp get cd_harps t --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdu' 'z "$(harp get cd_harps u --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdv' 'z "$(harp get cd_harps v --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdw' 'z "$(harp get cd_harps w --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdx' 'z "$(harp get cd_harps x --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdy' 'z "$(harp get cd_harps y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdz' 'z "$(harp get cd_harps z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind ',sdA' 'z "$(harp get cd_harps A --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdB' 'z "$(harp get cd_harps B --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdC' 'z "$(harp get cd_harps C --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdD' 'z "$(harp get cd_harps D --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdE' 'z "$(harp get cd_harps E --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdF' 'z "$(harp get cd_harps F --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdG' 'z "$(harp get cd_harps G --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdH' 'z "$(harp get cd_harps H --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdI' 'z "$(harp get cd_harps I --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdJ' 'z "$(harp get cd_harps J --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdK' 'z "$(harp get cd_harps K --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdL' 'z "$(harp get cd_harps L --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdM' 'z "$(harp get cd_harps M --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdN' 'z "$(harp get cd_harps N --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdO' 'z "$(harp get cd_harps O --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdP' 'z "$(harp get cd_harps P --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdQ' 'z "$(harp get cd_harps Q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdR' 'z "$(harp get cd_harps R --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdS' 'z "$(harp get cd_harps S --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdT' 'z "$(harp get cd_harps T --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdU' 'z "$(harp get cd_harps U --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdV' 'z "$(harp get cd_harps V --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdW' 'z "$(harp get cd_harps W --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdX' 'z "$(harp get cd_harps X --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdY' 'z "$(harp get cd_harps Y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sdZ' 'z "$(harp get cd_harps Z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind ',sd1' 'z "$(harp get cd_harps 1 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd2' 'z "$(harp get cd_harps 2 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd3' 'z "$(harp get cd_harps 3 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd4' 'z "$(harp get cd_harps 4 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd5' 'z "$(harp get cd_harps 5 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd6' 'z "$(harp get cd_harps 6 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd7' 'z "$(harp get cd_harps 7 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd8' 'z "$(harp get cd_harps 8 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd9' 'z "$(harp get cd_harps 9 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind ',sd0' 'z "$(harp get cd_harps 0 --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind ',Sda' 'harp update cd_harps a --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark a ; commandline -f repaint'
bind ',Sdb' 'harp update cd_harps b --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark b ; commandline -f repaint'
bind ',Sdc' 'harp update cd_harps c --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark c ; commandline -f repaint'
bind ',Sdd' 'harp update cd_harps d --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark d ; commandline -f repaint'
bind ',Sde' 'harp update cd_harps e --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark e ; commandline -f repaint'
bind ',Sdf' 'harp update cd_harps f --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark f ; commandline -f repaint'
bind ',Sdg' 'harp update cd_harps g --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark g ; commandline -f repaint'
bind ',Sdh' 'harp update cd_harps h --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark h ; commandline -f repaint'
bind ',Sdi' 'harp update cd_harps i --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark i ; commandline -f repaint'
bind ',Sdj' 'harp update cd_harps j --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark j ; commandline -f repaint'
bind ',Sdk' 'harp update cd_harps k --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark k ; commandline -f repaint'
bind ',Sdl' 'harp update cd_harps l --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark l ; commandline -f repaint'
bind ',Sdm' 'harp update cd_harps m --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark m ; commandline -f repaint'
bind ',Sdn' 'harp update cd_harps n --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark n ; commandline -f repaint'
bind ',Sdo' 'harp update cd_harps o --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark o ; commandline -f repaint'
bind ',Sdp' 'harp update cd_harps p --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark p ; commandline -f repaint'
bind ',Sdq' 'harp update cd_harps q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark q ; commandline -f repaint'
bind ',Sdr' 'harp update cd_harps r --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark r ; commandline -f repaint'
bind ',Sds' 'harp update cd_harps s --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark s ; commandline -f repaint'
bind ',Sdt' 'harp update cd_harps t --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark t ; commandline -f repaint'
bind ',Sdu' 'harp update cd_harps u --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark u ; commandline -f repaint'
bind ',Sdv' 'harp update cd_harps v --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark v ; commandline -f repaint'
bind ',Sdw' 'harp update cd_harps w --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark w ; commandline -f repaint'
bind ',Sdx' 'harp update cd_harps x --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark x ; commandline -f repaint'
bind ',Sdy' 'harp update cd_harps y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark y ; commandline -f repaint'
bind ',Sdz' 'harp update cd_harps z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark z ; commandline -f repaint'

bind ',SdA' 'harp update cd_harps A --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark A ; commandline -f repaint'
bind ',SdB' 'harp update cd_harps B --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark B ; commandline -f repaint'
bind ',SdC' 'harp update cd_harps C --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark C ; commandline -f repaint'
bind ',SdD' 'harp update cd_harps D --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark D ; commandline -f repaint'
bind ',SdE' 'harp update cd_harps E --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark E ; commandline -f repaint'
bind ',SdF' 'harp update cd_harps F --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark F ; commandline -f repaint'
bind ',SdG' 'harp update cd_harps G --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark G ; commandline -f repaint'
bind ',SdH' 'harp update cd_harps H --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark H ; commandline -f repaint'
bind ',SdI' 'harp update cd_harps I --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark I ; commandline -f repaint'
bind ',SdJ' 'harp update cd_harps J --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark J ; commandline -f repaint'
bind ',SdK' 'harp update cd_harps K --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark K ; commandline -f repaint'
bind ',SdL' 'harp update cd_harps L --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark L ; commandline -f repaint'
bind ',SdM' 'harp update cd_harps M --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark M ; commandline -f repaint'
bind ',SdN' 'harp update cd_harps N --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark N ; commandline -f repaint'
bind ',SdO' 'harp update cd_harps O --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark O ; commandline -f repaint'
bind ',SdP' 'harp update cd_harps P --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark P ; commandline -f repaint'
bind ',SdQ' 'harp update cd_harps Q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Q ; commandline -f repaint'
bind ',SdR' 'harp update cd_harps R --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark R ; commandline -f repaint'
bind ',SdS' 'harp update cd_harps S --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark S ; commandline -f repaint'
bind ',SdT' 'harp update cd_harps T --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark T ; commandline -f repaint'
bind ',SdU' 'harp update cd_harps U --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark U ; commandline -f repaint'
bind ',SdV' 'harp update cd_harps V --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark V ; commandline -f repaint'
bind ',SdW' 'harp update cd_harps W --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark W ; commandline -f repaint'
bind ',SdX' 'harp update cd_harps X --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark X ; commandline -f repaint'
bind ',SdY' 'harp update cd_harps Y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Y ; commandline -f repaint'
bind ',SdZ' 'harp update cd_harps Z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Z ; commandline -f repaint'

bind ',Sd1' 'harp update cd_harps 1 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 1 ; commandline -f repaint'
bind ',Sd2' 'harp update cd_harps 2 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 2 ; commandline -f repaint'
bind ',Sd3' 'harp update cd_harps 3 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 3 ; commandline -f repaint'
bind ',Sd4' 'harp update cd_harps 4 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 4 ; commandline -f repaint'
bind ',Sd5' 'harp update cd_harps 5 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 5 ; commandline -f repaint'
bind ',Sd6' 'harp update cd_harps 6 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 6 ; commandline -f repaint'
bind ',Sd7' 'harp update cd_harps 7 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 7 ; commandline -f repaint'
bind ',Sd8' 'harp update cd_harps 8 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 8 ; commandline -f repaint'
bind ',Sd9' 'harp update cd_harps 9 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 9 ; commandline -f repaint'
bind ',Sd0' 'harp update cd_harps 0 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 0 ; commandline -f repaint'
