bind '"a' 'z "$(harp get cd_harps a --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"b' 'z "$(harp get cd_harps b --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"c' 'z "$(harp get cd_harps c --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"d' 'z "$(harp get cd_harps d --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"e' 'z "$(harp get cd_harps e --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"f' 'z "$(harp get cd_harps f --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"g' 'z "$(harp get cd_harps g --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"h' 'z "$(harp get cd_harps h --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"i' 'z "$(harp get cd_harps i --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"j' 'z "$(harp get cd_harps j --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"k' 'z "$(harp get cd_harps k --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"l' 'z "$(harp get cd_harps l --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"m' 'z "$(harp get cd_harps m --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"n' 'z "$(harp get cd_harps n --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"o' 'z "$(harp get cd_harps o --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"p' 'z "$(harp get cd_harps p --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"q' 'z "$(harp get cd_harps q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"r' 'z "$(harp get cd_harps r --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"s' 'z "$(harp get cd_harps s --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"t' 'z "$(harp get cd_harps t --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"u' 'z "$(harp get cd_harps u --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"v' 'z "$(harp get cd_harps v --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"w' 'z "$(harp get cd_harps w --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"x' 'z "$(harp get cd_harps x --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"y' 'z "$(harp get cd_harps y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"z' 'z "$(harp get cd_harps z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind '"A' 'z "$(harp get cd_harps A --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"B' 'z "$(harp get cd_harps B --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"C' 'z "$(harp get cd_harps C --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"D' 'z "$(harp get cd_harps D --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"E' 'z "$(harp get cd_harps E --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"F' 'z "$(harp get cd_harps F --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"G' 'z "$(harp get cd_harps G --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"H' 'z "$(harp get cd_harps H --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"I' 'z "$(harp get cd_harps I --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"J' 'z "$(harp get cd_harps J --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"K' 'z "$(harp get cd_harps K --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"L' 'z "$(harp get cd_harps L --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"M' 'z "$(harp get cd_harps M --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"N' 'z "$(harp get cd_harps N --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"O' 'z "$(harp get cd_harps O --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"P' 'z "$(harp get cd_harps P --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"Q' 'z "$(harp get cd_harps Q --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"R' 'z "$(harp get cd_harps R --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"S' 'z "$(harp get cd_harps S --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"T' 'z "$(harp get cd_harps T --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"U' 'z "$(harp get cd_harps U --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"V' 'z "$(harp get cd_harps V --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"W' 'z "$(harp get cd_harps W --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"X' 'z "$(harp get cd_harps X --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"Y' 'z "$(harp get cd_harps Y --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"Z' 'z "$(harp get cd_harps Z --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind '"1' 'z "$(harp get cd_harps 1 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"2' 'z "$(harp get cd_harps 2 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"3' 'z "$(harp get cd_harps 3 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"4' 'z "$(harp get cd_harps 4 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"5' 'z "$(harp get cd_harps 5 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"6' 'z "$(harp get cd_harps 6 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"7' 'z "$(harp get cd_harps 7 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"8' 'z "$(harp get cd_harps 8 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"9' 'z "$(harp get cd_harps 9 --path | string replace \\~ $HOME)" ; commandline -f repaint'
bind '"0' 'z "$(harp get cd_harps 0 --path | string replace \\~ $HOME)" ; commandline -f repaint'

bind '""a' 'harp update cd_harps a --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark a ; commandline -f repaint'
bind '""b' 'harp update cd_harps b --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark b ; commandline -f repaint'
bind '""c' 'harp update cd_harps c --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark c ; commandline -f repaint'
bind '""d' 'harp update cd_harps d --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark d ; commandline -f repaint'
bind '""e' 'harp update cd_harps e --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark e ; commandline -f repaint'
bind '""f' 'harp update cd_harps f --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark f ; commandline -f repaint'
bind '""g' 'harp update cd_harps g --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark g ; commandline -f repaint'
bind '""h' 'harp update cd_harps h --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark h ; commandline -f repaint'
bind '""i' 'harp update cd_harps i --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark i ; commandline -f repaint'
bind '""j' 'harp update cd_harps j --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark j ; commandline -f repaint'
bind '""k' 'harp update cd_harps k --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark k ; commandline -f repaint'
bind '""l' 'harp update cd_harps l --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark l ; commandline -f repaint'
bind '""m' 'harp update cd_harps m --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark m ; commandline -f repaint'
bind '""n' 'harp update cd_harps n --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark n ; commandline -f repaint'
bind '""o' 'harp update cd_harps o --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark o ; commandline -f repaint'
bind '""p' 'harp update cd_harps p --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark p ; commandline -f repaint'
bind '""q' 'harp update cd_harps q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark q ; commandline -f repaint'
bind '""r' 'harp update cd_harps r --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark r ; commandline -f repaint'
bind '""s' 'harp update cd_harps s --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark s ; commandline -f repaint'
bind '""t' 'harp update cd_harps t --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark t ; commandline -f repaint'
bind '""u' 'harp update cd_harps u --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark u ; commandline -f repaint'
bind '""v' 'harp update cd_harps v --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark v ; commandline -f repaint'
bind '""w' 'harp update cd_harps w --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark w ; commandline -f repaint'
bind '""x' 'harp update cd_harps x --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark x ; commandline -f repaint'
bind '""y' 'harp update cd_harps y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark y ; commandline -f repaint'
bind '""z' 'harp update cd_harps z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark z ; commandline -f repaint'

bind '""A' 'harp update cd_harps A --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark A ; commandline -f repaint'
bind '""B' 'harp update cd_harps B --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark B ; commandline -f repaint'
bind '""C' 'harp update cd_harps C --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark C ; commandline -f repaint'
bind '""D' 'harp update cd_harps D --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark D ; commandline -f repaint'
bind '""E' 'harp update cd_harps E --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark E ; commandline -f repaint'
bind '""F' 'harp update cd_harps F --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark F ; commandline -f repaint'
bind '""G' 'harp update cd_harps G --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark G ; commandline -f repaint'
bind '""H' 'harp update cd_harps H --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark H ; commandline -f repaint'
bind '""I' 'harp update cd_harps I --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark I ; commandline -f repaint'
bind '""J' 'harp update cd_harps J --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark J ; commandline -f repaint'
bind '""K' 'harp update cd_harps K --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark K ; commandline -f repaint'
bind '""L' 'harp update cd_harps L --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark L ; commandline -f repaint'
bind '""M' 'harp update cd_harps M --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark M ; commandline -f repaint'
bind '""N' 'harp update cd_harps N --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark N ; commandline -f repaint'
bind '""O' 'harp update cd_harps O --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark O ; commandline -f repaint'
bind '""P' 'harp update cd_harps P --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark P ; commandline -f repaint'
bind '""Q' 'harp update cd_harps Q --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Q ; commandline -f repaint'
bind '""R' 'harp update cd_harps R --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark R ; commandline -f repaint'
bind '""S' 'harp update cd_harps S --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark S ; commandline -f repaint'
bind '""T' 'harp update cd_harps T --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark T ; commandline -f repaint'
bind '""U' 'harp update cd_harps U --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark U ; commandline -f repaint'
bind '""V' 'harp update cd_harps V --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark V ; commandline -f repaint'
bind '""W' 'harp update cd_harps W --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark W ; commandline -f repaint'
bind '""X' 'harp update cd_harps X --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark X ; commandline -f repaint'
bind '""Y' 'harp update cd_harps Y --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Y ; commandline -f repaint'
bind '""Z' 'harp update cd_harps Z --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark Z ; commandline -f repaint'

bind '""1' 'harp update cd_harps 1 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 1 ; commandline -f repaint'
bind '""2' 'harp update cd_harps 2 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 2 ; commandline -f repaint'
bind '""3' 'harp update cd_harps 3 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 3 ; commandline -f repaint'
bind '""4' 'harp update cd_harps 4 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 4 ; commandline -f repaint'
bind '""5' 'harp update cd_harps 5 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 5 ; commandline -f repaint'
bind '""6' 'harp update cd_harps 6 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 6 ; commandline -f repaint'
bind '""7' 'harp update cd_harps 7 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 7 ; commandline -f repaint'
bind '""8' 'harp update cd_harps 8 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 8 ; commandline -f repaint'
bind '""9' 'harp update cd_harps 9 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 9 ; commandline -f repaint'
bind '""0' 'harp update cd_harps 0 --path "$(pwd | string replace $HOME \\~)" ; echo set bookmark 0 ; commandline -f repaint'
