'attribute' = 'mint'
'comment' = 'grey0'
'constant' = 'purple'
'constant.character.escape' = 'orange'
'constant.numeric' = 'blush'
'constructor' = 'yellow'
'function' = 'green'
'function.builtin' = 'cyan'
'function.macro' = 'mint'
'keyword' = 'red'
'keyword.directive' = 'mint'
'label' = 'mint'
'module' = 'cyan'
'namespace' = 'mint'
'operator' = 'orange'
'punctuation' = 'grey2'
'punctuation.bracket' = 'white'
'punctuation.delimiter' = 'grey2'
'special' = 'orange'
'string' = 'yellow'
'string.regexp' = 'cyan'
'tag' = 'yellow'
'type' = 'cyan'
'variable' = 'white'
'variable.builtin' = 'cyan'
'variable.other.member' = 'white'
'variable.parameter' = 'white'

'markup.heading.marker' = 'grey2'
'markup.heading.1' = { fg = 'red', modifiers = ['bold'] }
'markup.heading.2' = { fg = 'orange', modifiers = ['bold'] }
'markup.heading.3' = { fg = 'yellow', modifiers = ['bold'] }
'markup.heading.4' = { fg = 'green', modifiers = ['bold'] }
'markup.heading.5' = { fg = 'cyan', modifiers = ['bold'] }
'markup.heading.6' = { fg = 'white', modifiers = ['bold'] }
'markup.list' = 'red'
'markup.bold' = { modifiers = ['bold'] }
'markup.italic' = { modifiers = ['italic'] }
'markup.link.url' = { fg = 'cyan', modifiers = ['underlined'] }
'markup.link.text' = 'purple'
'markup.quote' = 'grey2'
'markup.raw' = 'green'

'diff.plus' = 'green'
'diff.delta' = 'orange'
'diff.minus' = 'red'

'ui.background' = { bg = 'level' }
'ui.background.separator' = 'grey0'
'ui.cursor' = { fg = 'level', bg = 'white' }
'ui.cursor.match' = { fg = 'orange', bg = 'bg_visual_yellow' }
'ui.cursor.insert' = { fg = 'level', bg = 'grey2' }
'ui.cursor.select' = { fg = 'level', bg = 'cyan' }
'ui.cursorline.primary' = { bg = 'bg1' }
'ui.cursorline.secondary' = { bg = 'bg1' }
'ui.selection' = { bg = 'bg3' }
'ui.linenr' = 'grey0'
'ui.linenr.selected' = 'white'
'ui.statusline' = { fg = 'white', bg = 'bg3' }
'ui.statusline.inactive' = { fg = 'grey0', bg = 'bg1' }
'ui.statusline.normal' = { fg = 'level', bg = 'white', modifiers = ['bold'] }
'ui.statusline.insert' = { fg = 'level', bg = 'yellow', modifiers = ['bold'] }
'ui.statusline.select' = { fg = 'level', bg = 'cyan', modifiers = ['bold'] }
'ui.bufferline' = { fg = 'grey0', bg = 'bg1' }
'ui.bufferline.active' = { fg = 'white', bg = 'bg3', modifiers = ['bold'] }
'ui.popup' = { fg = 'grey2', bg = 'bg2' }
'ui.window' = { fg = 'grey0', bg = 'level' }
'ui.help' = { fg = 'white', bg = 'bg2' }
'ui.text' = 'white'
'ui.text.focus' = 'white'
'ui.menu' = { fg = 'white', bg = 'bg3' }
'ui.menu.selected' = { fg = 'level', bg = 'cyan', modifiers = ['bold'] }
'ui.virtual.whitespace' = { fg = 'bg4' }
'ui.virtual.indent-guide' = { fg = 'bg4' }
'ui.virtual.ruler' = { bg = 'bg3' }

'hint' = 'cyan'
'info' = 'mint'
'warning' = 'yellow'
'error' = 'red'
'diagnostic' = { underline = { style = 'curl' } }
'diagnostic.hint' = { underline = { color = 'cyan', style = 'dotted' } }
'diagnostic.info' = { underline = { color = 'mint', style = 'dotted' } }
'diagnostic.warning' = { underline = { color = 'yellow', style = 'curl' } }
'diagnostic.error' = { underline = { color = 'red', style = 'curl' } }

[palette]

level = '#292828'
bg1 = '#32302f'
bg2 = '#32302f'
bg3 = '#45403d'
bg4 = '#45403d'
bg5 = '#5a524c'
bg_statusline1 = '#32302f'
bg_statusline2 = '#3a3735'
bg_statusline3 = '#504945'
bg_diff_green = '#34381b'
bg_visual_green = '#3b4439'
bg_diff_red = '#402120'
bg_visual_red = '#4c3432'
bg_diff_cyan = '#0e363e'
bg_visual_cyan = '#374141'
bg_visual_yellow = '#4f422e'
bg_current_word = '#3c3836'

white = '#d4be98'
whiter = '#ddc7a1'
red = '#ea6962'
orange = '#e49641'
yellow = '#d3ad5c'
green = '#a9b665'
mint = '#89b482'
cyan = '#7daea3'
blush = '#e491b2'
purple = '#b58cc6'

grey0 = '#7c6f64'
grey = '#928374'
grey2 = '#a89984'
