---@type LazySpec
return {
	{ 'stevearc/resession.nvim', enabled = false },
	{ 'mfussenegger/nvim-dap-python', enabled = false },
	{ 'lukas-reineke/indent-blankline.nvim', enabled = false },
	{ 'JoosepAlviste/nvim-ts-context-commentstring', enabled = false },
	{ 's1n7ax/nvim-window-picker', enabled = false },
	-- { 'numToStr/Comment.nvim', enabled = false },
	{ 'RRethy/vim-illuminate', enabled = false },
	{ 'mfussenegger/nvim-dap', enabled = false },
	{ 'folke/todo-comments.nvim', enabled = false },
	{ 'goolord/alpha-nvim', enabled = false },
	{ 'max397574/better-escape.nvim', enabled = false },
	{ 'folke/which-key.nvim', enabled = false },
	{ 'rafamadriz/friendly-snippets', enabled = false },
	{ 'nvim-neo-tree/neo-tree.nvim', enabled = false },
	{ 'akinsho/toggleterm.nvim', enabled = false },
	{ 'kevinhwang91/nvim-ufo', enabled = false },
	{ 'mrjones2014/smart-splits.nvim', enabled = false },
	{ 'stevearc/aerial.nvim', enabled = false },
	{ 'jay-babu/mason-nvim-dap.nvim', enabled = false },
	{ 'jay-babu/mason-null-ls.nvim', enabled = false },
	{ 'nvimtools/none-ls.nvim', enabled = false },
}
