---@type LazySpec
return {
	'AstroNvim/astrocommunity',
	-- { import = 'astrocommunity.pack.cs' },
	-- { import = 'astrocommunity.pack.lua' },
	-- { import = 'astrocommunity.pack.nim' },
	-- { import = 'astrocommunity.pack.sql' },
	{ import = 'astrocommunity.color.ccc-nvim' },
	-- { import = 'astrocommunity.editing-support.conform-nvim' },
	{ import = 'astrocommunity.lsp.nvim-lint' },
	{ import = 'astrocommunity.file-explorer.oil-nvim' },
	{ import = 'astrocommunity.fuzzy-finder.telescope-zoxide' },
	{ import = 'astrocommunity.motion.nvim-surround' },
	{ import = 'astrocommunity.pack.fish' },
	{ import = 'astrocommunity.pack.html-css' },
	{ import = 'astrocommunity.pack.json' },
	{ import = 'astrocommunity.pack.markdown' },
	{ import = 'astrocommunity.pack.python' },
	{ import = 'astrocommunity.pack.rust' },
	{ import = 'astrocommunity.pack.toml' },
	{ import = 'astrocommunity.pack.yaml' },
}
