#!/usr/bin/bash

sudo pacman -Syu

# Themes
sudo pacman -S --noconfirm breeze-icons
sudo pacman -S --noconfirm ttf-jetbrains-mono-nerd
sudo pacman -S --noconfirm ttf-ubuntu-nerd
sudo pacman -S --noconfirm lxappearance
sudo pacman -S --noconfirm gtk-engine-murrine
sudo pacman -S --noconfirm papirus-icon-theme
sudo pacman -S --noconfirm otf-monaspace-nerd

sudo pacman -S --noconfirm paru
sudo pacman -S --noconfirm vivaldi
sudo pacman -S --noconfirm fzf
sudo pacman -S --noconfirm hyfetch
sudo pacman -S --noconfirm cmatrix
sudo pacman -S --noconfirm cowsay
sudo pacman -S --noconfirm libssl-dev
sudo pacman -S --noconfirm curl
sudo pacman -S --noconfirm xclip
sudo pacman -S --noconfirm github-cli
sudo pacman -S --noconfirm dotnet-runtime dotnet-sdk aspnet-runtime
sudo pacman -S --noconfirm spotify-launcher
sudo pacman -S --noconfirm ffmpeg
sudo pacman -S --noconfirm neovim
sudo pacman -S --noconfirm fish
sudo pacman -S --noconfirm kitty
sudo pacman -S --noconfirm tokei
sudo pacman -S --noconfirm zoxide
sudo pacman -S --noconfirm sd
sudo pacman -S --noconfirm screenkey
sudo pacman -S --noconfirm kid3
sudo pacman -S --noconfirm kwalletmanager
sudo pacman -S --noconfirm packagekit-qt5
sudo pacman -S --noconfirm espeak-ng
sudo pacman -S --noconfirm imagemagick
sudo pacman -S --noconfirm lolcat
sudo pacman -S --noconfirm kruler
sudo pacman -S --noconfirm scrot
sudo pacman -S --noconfirm zip
sudo pacman -S --noconfirm wine-mono
sudo pacman -S --noconfirm traceroute
sudo pacman -S --noconfirm xdotool
sudo pacman -S --noconfirm steam
sudo pacman -S --noconfirm vulkan-radeon
sudo pacman -S --noconfirm lib32-vulkan-radeon
sudo pacman -S --noconfirm samba
sudo pacman -S --noconfirm zathura
sudo pacman -S --noconfirm zathura-pdf-mupdf
sudo pacman -S --noconfirm devtools
sudo pacman -S --noconfirm wmctrl
sudo pacman -S --noconfirm ydotool
sudo pacman -S --noconfirm libreoffice-still
sudo pacman -S --noconfirm sl
sudo pacman -S --noconfirm diff-so-fancy
sudo pacman -S --noconfirm yt-dlp
sudo pacman -S --noconfirm python-mutagen
sudo pacman -S --noconfirm cargo-binstall
sudo pacman -S --noconfirm ripgrep
sudo pacman -S --noconfirm fd
sudo pacman -S --noconfirm cargo-update
sudo pacman -S --noconfirm bacon
sudo pacman -S --noconfirm ollama
sudo pacman -S --noconfirm rustup
sudo pacman -S --noconfirm pastel
sudo pacman -S --noconfirm postgresql
sudo pacman -S --noconfirm ufw
sudo pacman -S --noconfirm go
sudo pacman -S --noconfirm python-pillow
sudo pacman -S --noconfirm awesome
sudo pacman -S --noconfirm xorg-xev
sudo pacman -S --noconfirm python3
sudo pacman -S --noconfirm python-pip
sudo pacman -S --noconfirm python-pipx
sudo pacman -S --noconfirm sddm
sudo pacman -S --noconfirm termdown
sudo pacman -S --noconfirm redshift
sudo pacman -S --noconfirm picom
sudo pacman -S --noconfirm kruler
sudo pacman -S --noconfirm obs-studio
sudo pacman -S --noconfirm gimp
sudo pacman -S --noconfirm rofi
sudo pacman -S --noconfirm bat
sudo pacman -S --noconfirm trash-cli
sudo pacman -S --noconfirm speedtest-cli
sudo pacman -S --noconfirm mpv
sudo pacman -S --noconfirm tree-sitter-cli
sudo pacman -S --noconfirm dust
sudo pacman -S --noconfirm playerctl
sudo pacman -S --noconfirm nim
sudo pacman -S --noconfirm alacritty
sudo pacman -S --noconfirm sysstat
sudo pacman -S --noconfirm xsel
sudo pacman -S --noconfirm acpi
sudo pacman -S --noconfirm eza
sudo pacman -S --noconfirm tidy
sudo pacman -S --noconfirm luarocks
sudo pacman -S --noconfirm whois
sudo pacman -S --noconfirm copyq
sudo pacman -S --noconfirm httrack
sudo pacman -S --noconfirm asciinema
sudo pacman -S --noconfirm pueue