#!/usr/bin/bash

sudo pacman -Syu --noconfirm tree
sudo pacman -S --noconfirm fzf
sudo pacman -S --noconfirm hyfetch
sudo pacman -S --noconfirm ncdu
sudo pacman -S --noconfirm cmatrix
sudo pacman -S --noconfirm cowsay
sudo pacman -S --noconfirm libssl-dev
sudo pacman -S --noconfirm curl
sudo pacman -S --noconfirm xclip
sudo pacman -S --noconfirm ttf-jetbrains-mono-nerd
sudo pacman -S --noconfirm ttf-ubuntu-nerd
sudo pacman -S --noconfirm github-cli
sudo pacman -S --noconfirm dotnet-runtime dotnet-sdk aspnet-runtime
sudo pacman -S --noconfirm spotify-launcher
sudo pacman -S --noconfirm ffmpeg
sudo pacman -S --noconfirm neovim
sudo pacman -S --noconfirm fish
sudo pacman -S --noconfirm kitty
sudo pacman -S --noconfirm ranger
sudo pacman -S --noconfirm tokei
sudo pacman -S --noconfirm zoxide
sudo pacman -S --noconfirm sd
sudo pacman -S --noconfirm screenkey slop
sudo pacman -S --noconfirm kid3
sudo pacman -S --noconfirm kwalletmanager
sudo pacman -S --noconfirm packagekit-qt5
sudo pacman -S --noconfirm espeak-ng
sudo pacman -S --noconfirm imagemagick
sudo pacman -S --noconfirm haruna
sudo pacman -S --noconfirm btop
sudo pacman -S --noconfirm kdeplasma-addons
sudo pacman -S --noconfirm lolcat
sudo pacman -S --noconfirm kruler
sudo pacman -S --noconfirm filezilla
sudo pacman -S --noconfirm scrot
sudo pacman -S --noconfirm zip
sudo pacman -S --noconfirm wine-mono
sudo pacman -S --noconfirm traceroute
sudo pacman -S --noconfirm xdotool
sudo pacman -S --noconfirm steam
sudo pacman -S --noconfirm vulkan-radeon
sudo pacman -S --noconfirm lib32-vulkan-radeon
sudo pacman -S --noconfirm samba
sudo pacman -S --noconfirm zathura
sudo pacman -S --noconfirm zathura-pdf-mupdf
sudo pacman -S --noconfirm devtools
sudo pacman -S --noconfirm wmctrl
sudo pacman -S --noconfirm ydotool
sudo pacman -S --noconfirm libreoffice-still