virtual_modifiers:
  - Tab
default_mode: default
modmap:
  - remap:
      CapsLock: Esc
      Esc: F13
      Compose: Super_R # For me, Compose is the Menu key

  - name: Game side mouse buttons fix
    remap:
      Btn_Side: k
      Btn_Extra: j
    application:
      only: /Terraria/

keymap:
  - name: Tile and focus input
    remap:
      Tab-b: ["super-8", "shift-tab", "shift-tab", "shift-tab", "shift-tab"] # banking on #8 toggling float
    application:
      only: Anki

  - name: Kde Compose key
    remap:
      Shift-Esc: insert

  - name: Direct mouse
    remap:
      Tab-LeftBrace: { launch: ["ydotool", "click", "c0"] } # c0 — left click
      Tab-RightBrace: { launch: ["ydotool", "click", "c1"] } # c1 — right click
      Tab-m: { launch: ["ydotool", "mousemove", "-w", "--", "-1", "0"] } # left
      Tab-Comma: { launch: ["ydotool", "mousemove", "-w", "--", "0", "1"] } # up
      Tab-Dot: { launch: ["ydotool", "mousemove", "-w", "--", "0", "-1"] } # down
      Tab-Slash: { launch: ["ydotool", "mousemove", "-w", "--", "1", "0"] } # up

  - name: Kill focused process (kills all instances of a browser, for example)
    remap:
      Tab-d: { launch: [xdotool, getwindowfocus, windowkill] }

  - name: Gromit
    remap:
      Super-f: { launch: [gromit-mpx, -t] }
      Super-Alt-f: { launch: [gromit-mpx, -c] }
      Super-g: { launch: [gromit-mpx, -t, -c] }

  - name: Edit clipboard
    remap:
      Super-e:
        {
          launch:
            [
              sh,
              -c,
              "xclip -selection clipboard -o > /tmp/bibren ; kitty -T edit-clipboard nvim -n /tmp/bibren ; test -s /tmp/bibren && cat /tmp/bibren | xclip -r -selection clipboard",
            ],
        }
      Super-Alt-e:
        {
          launch:
            [
              sh,
              -c,
              "truncate -s 0 /tmp/bibren ; kitty -T edit-clipboard nvim -n /tmp/bibren ; test -s /tmp/bibren && cat /tmp/bibren | xclip -r -selection clipboard",
            ],
        }

  - name: Pick unicode
    remap:
      Super-Alt-Semicolon:
        {
          launch:
            [
              sh,
              -c,
              'kitty -T emoji-picker --start-as maximized sh -c "kitty +kitten unicode_input --tab code > /tmp/unicode_input" ; cat /tmp/unicode_input | xclip -r -selection clipboard',
            ],
        }

  - name: Float image in clipboard
    remap:
      Super-w:
        {
          launch:
            [
              fish,
              -c,
              "xclip -selection clipboard -t image/png -o 2>/dev/null | display",
            ],
        }

  - name: Put three random words to clipboard
    remap:
      Super-5:
        { launch: [sh, -c, "uclanr -tj '' 3 | xclip -r -selection clipboard"] }

  - name: Stdin typer
    remap:
      Super-n: { launch: [sh, -c, "kitty --detach --hold -T infoterm holup"] }

  - name: Kitty
    remap:
      Super-r: { launch: [kitty] }
      Super-Alt-r: { launch: [kitty, -T, temporary-terminal] }

  - name: Screenkey
    remap:
      Super-3: { launch: [screenkey] }
      Super-Alt-3: { launch: [killall, screenkey] }

  - name: Default mode
    remap:
      Tab-Semicolon: { set_mode: vim }
    mode: default

  - name: Vim mode
    remap:
      Tab-Semicolon: { set_mode: default }

      q: { launch: [xdotool, mousemove, '160',  '135']}
      w: { launch: [xdotool, mousemove, '560',  '135']}
      e: { launch: [xdotool, mousemove, '960',  '135']}
      r: { launch: [xdotool, mousemove, '1360', '135']}
      t: { launch: [xdotool, mousemove, '1760', '135']}

      a: { launch: [xdotool, mousemove, '160',  '540']}
      s: { launch: [xdotool, mousemove, '560',  '540']}
      d: { launch: [xdotool, mousemove, '960',  '540']}
      f: { launch: [xdotool, mousemove, '1360', '540']}
      g: { launch: [xdotool, mousemove, '1760', '540']}

      z: { launch: [xdotool, mousemove, '160',  '945']}
      x: { launch: [xdotool, mousemove, '560',  '945']}
      c: { launch: [xdotool, mousemove, '960',  '945']}
      v: { launch: [xdotool, mousemove, '1360', '945']}
      b: { launch: [xdotool, mousemove, '1760', '945']}

      h: { launch: [ydotool, mousemove, '--', '-5', '0']}
      l: { launch: [ydotool, mousemove, '--', '5', '0']}
      j: { launch: [ydotool, mousemove, '--', '0', '5']}
      k: { launch: [ydotool, mousemove, '--', '0', '-5']}

      Shift-h: { launch: [ydotool, mousemove, '--', '-20', '0']}
      Shift-l: { launch: [ydotool, mousemove, '--', '20', '0']}
      Shift-j: { launch: [ydotool, mousemove, '--', '0', '20']}
      Shift-k: { launch: [ydotool, mousemove, '--', '0', '-20']}

      Alt-h: { launch: [ydotool, mousemove, '--', '-50', '0']}
      Alt-l: { launch: [ydotool, mousemove, '--', '50', '0']}
      Alt-j: { launch: [ydotool, mousemove, '--', '0', '50']}
      Alt-k: { launch: [ydotool, mousemove, '--', '0', '-50']}

    mode: vim

  - remap:
      Tab-t: tab
      Tab-Backspace: delete
      Tab-q: delete

      Tab-h: left
      Tab-j: down
      Tab-k: up
      Tab-l: right
      Tab-i: home
      Tab-o: end
      Tab-u: pageup
      Tab-p: pagedown

      Tab-w: ctrl-c
      Tab-s: ctrl-x
      Tab-e: ctrl-v
      Tab-r: ctrl-a