virtual_modifiers:
  - Tab
modmap:
  - remap:
      CapsLock: Esc
      Esc: Delete
  - name: Game side mouse buttons fix
    remap:
      Btn_Side: k
      Btn_Extra: j
    application:
      only: /Terraria/
keymap:
  - remap:
      Tab-t: Tab
      Tab-h: left
      Tab-j: down
      Tab-k: up
      Tab-l: right
      Tab-i: home
      Tab-o: end
      Tab-u: pageup
      Tab-p: pagedown
      Tab-w: ctrl-insert
      Tab-e: shift-insert
      Tab-r: ctrl-a

      Super-Esc: { launch: ["xdotool", "getwindowfocus", "windowkill"] }
      # Show image in clipboard
      Super-w:
        {
          launch:
            [
              "bash",
              "-c",
              "xclip -selection clipboard -t image/png -o 2>/dev/null | display",
            ],
        }
