virtual_modifiers:
  - CapsLock
default_mode: default
modmap:
  - remap:
      Tab: Esc
      Esc: F13
      Compose: Super_R # For me, Compose is the Menu key

  - name: Game side mouse buttons fix
    remap:
      Btn_Side: k
      Btn_Extra: j
    application:
      only: /Terraria/

keymap:
  - name: Tile and focus input
    remap:
      CapsLock-b: ["super-8", "shift-tab", "shift-tab", "shift-tab", "shift-tab"] # banking on #8 toggling float
    application:
      only: Anki

  - name: Kde Compose key
    remap:
      CapsLock-Apostrophe: CapsLock

  - name: Kill focused process (kills all instances of a browser, for example)
    remap:
      CapsLock-q: { launch: [wmctrl, -c, ':ACTIVE:'] }
      CapsLock-Shift-q: { launch: [xdotool, getwindowfocus, windowkill] }

  - name: Gromit
    remap:
      Super-f: { launch: [gromit-mpx, -t] }
      Super-Alt-f: { launch: [gromit-mpx, -c] }
      Super-g: { launch: [gromit-mpx, -t, -c] }

  - name: Edit clipboard
    remap:
      CapsLock-Dot:
        {
          launch:
            [
              sh,
              -c,
              "xclip -selection clipboard -o > /tmp/bibren ; kitty -T edit-clipboard nvim -n /tmp/bibren ; test -s /tmp/bibren && cat /tmp/bibren | xclip -r -selection clipboard",
            ],
        }
      CapsLock-Alt-Dot:
        {
          launch:
            [
              sh,
              -c,
              "truncate -s 0 /tmp/bibren ; kitty -T edit-clipboard nvim -n /tmp/bibren ; test -s /tmp/bibren && cat /tmp/bibren | xclip -r -selection clipboard",
            ],
        }

  - name: Pick unicode
    remap:
      CapsLock-m:
        {
          launch:
            [
              sh,
              -c,
              'kitty -T emoji-picker --start-as maximized sh -c "kitty +kitten unicode_input --tab code > /tmp/unicode_input" ; cat /tmp/unicode_input | xclip -r -selection clipboard',
            ],
        }

  - name: Float image in clipboard
    remap:
      Super-w:
        {
          launch:
            [
              fish,
              -c,
              "xclip -selection clipboard -t image/png -o 2>/dev/null | display",
            ],
        }

  - name: Put three random words to clipboard
    remap:
      Super-5:
        { launch: [sh, -c, "uclanr -tj '' 3 | xclip -r -selection clipboard"] }

  - name: Stdin typer
    remap:
      CapsLock-Comma: { launch: [sh, -c, "kitty --detach --hold -T infoterm holup"] }

  - name: Kitty
    remap:
      Super-r: { launch: [kitty] }
      Super-Alt-r: { launch: [kitty, -T, temporary-terminal] }

  - name: Screenkey
    remap:
      Super-3: { launch: [screenkey] }
      Super-Alt-3: { launch: [killall, screenkey] }

  - name: Default mode
    remap:
      CapsLock-Semicolon: { set_mode: vim }
    mode: default

  - name: Vim mode
    remap:
      CapsLock-Semicolon: { set_mode: default }

      q: { launch: [xdotool, mousemove, '160',  '135']}
      w: { launch: [xdotool, mousemove, '560',  '135']}
      e: { launch: [xdotool, mousemove, '960',  '135']}
      r: { launch: [xdotool, mousemove, '1360', '135']}
      t: { launch: [xdotool, mousemove, '1760', '135']}

      a: { launch: [xdotool, mousemove, '160',  '540']}
      s: { launch: [xdotool, mousemove, '560',  '540']}
      d: { launch: [xdotool, mousemove, '960',  '540']}
      f: { launch: [xdotool, mousemove, '1360', '540']}
      g: { launch: [xdotool, mousemove, '1760', '540']}

      z: { launch: [xdotool, mousemove, '160',  '945']}
      x: { launch: [xdotool, mousemove, '560',  '945']}
      c: { launch: [xdotool, mousemove, '960',  '945']}
      v: { launch: [xdotool, mousemove, '1360', '945']}
      b: { launch: [xdotool, mousemove, '1760', '945']}

      h: { launch: [ydotool, mousemove, '--', '-5', '0']}
      l: { launch: [ydotool, mousemove, '--', '5', '0']}
      j: { launch: [ydotool, mousemove, '--', '0', '5']}
      k: { launch: [ydotool, mousemove, '--', '0', '-5']}

      Shift-h: { launch: [ydotool, mousemove, '--', '-20', '0']}
      Shift-l: { launch: [ydotool, mousemove, '--', '20', '0']}
      Shift-j: { launch: [ydotool, mousemove, '--', '0', '20']}
      Shift-k: { launch: [ydotool, mousemove, '--', '0', '-20']}
      CapsLock-h: { launch: [ydotool, mousemove, '--', '-20', '0']}
      CapsLock-l: { launch: [ydotool, mousemove, '--', '20', '0']}
      CapsLock-j: { launch: [ydotool, mousemove, '--', '0', '20']}
      CapsLock-k: { launch: [ydotool, mousemove, '--', '0', '-20']}

      Alt-h: { launch: [ydotool, mousemove, '--', '-50', '0']}
      Alt-l: { launch: [ydotool, mousemove, '--', '50', '0']}
      Alt-j: { launch: [ydotool, mousemove, '--', '0', '50']}
      Alt-k: { launch: [ydotool, mousemove, '--', '0', '-50']}
      Ctrl-h: { launch: [ydotool, mousemove, '--', '-50', '0']}
      Ctrl-l: { launch: [ydotool, mousemove, '--', '50', '0']}
      Ctrl-j: { launch: [ydotool, mousemove, '--', '0', '50']}
      Ctrl-k: { launch: [ydotool, mousemove, '--', '0', '-50']}

      u: { launch: ["ydotool", "click", "c0"] } # c0 — left click
      i: { launch: ["ydotool", "click", "c2"] } # c2 — middle click
      o: { launch: ["ydotool", "click", "c1"] } # c1 — right click

      # CapsLock-u: { launch: ["xdotool", "mousedown", "1"] }
      # CapsLock-i: { launch: ["xdotool", "mousedown", "2"] }
      # CapsLock-o: { launch: ["xdotool", "mousedown", "3"] }
      # CapsLock-7: { launch: ["xdotool", "mouseup", "1"] }
      # CapsLock-8: { launch: ["xdotool", "mouseup", "2"] }
      # CapsLock-9: { launch: ["xdotool", "mouseup", "3"] }

      CapsLock-u: { launch: ["ydotool", "click", "40"] }
      CapsLock-i: { launch: ["ydotool", "click", "42"] }
      CapsLock-o: { launch: ["ydotool", "click", "41"] }
      CapsLock-7: { launch: ["ydotool", "click", "80"] }
      CapsLock-8: { launch: ["ydotool", "click", "82"] }
      CapsLock-9: { launch: ["ydotool", "click", "81"] }

      # Holds down and up a modifier (the one aside from capslock):
      # j — down event
      # k — up event
      CapsLock-Super-j: { launch: [ydotool, key, '125:1'] }
      CapsLock-Super-k: { launch: [ydotool, key, '125:0'] }
      CapsLock-Shift-j: { launch: [ydotool, key, '42:1'] }
      CapsLock-Shift-k: { launch: [ydotool, key, '42:0'] }
      CapsLock-Alt-j:   { launch: [ydotool, key, '56:1'] }
      CapsLock-Alt-k:   { launch: [ydotool, key, '56:0'] }
      CapsLock-Ctrl-j:  { launch: [ydotool, key, '29:1'] }
      CapsLock-Ctrl-k:  { launch: [ydotool, key, '29:0'] }

      m: { launch: ["ydotool", "mousemove", "-w", "--", "-1", "0"] } # left
      Comma: { launch: ["ydotool", "mousemove", "-w", "--", "0", "1"] } # up
      Dot: { launch: ["ydotool", "mousemove", "-w", "--", "0", "-1"] } # down
      Slash: { launch: ["ydotool", "mousemove", "-w", "--", "1", "0"] } # up

    mode: vim

  - name: System & Media
    remap:
      CapsLock-Alt-s: { launch: [qdbus, org.kde.kglobalaccel, /component/kmix, invokeShortcut, decrease_volume] }
      CapsLock-Alt-d: { launch: [qdbus, org.kde.kglobalaccel, /component/kmix, invokeShortcut, increase_volume] }
      CapsLock-Alt-f: { launch: [qdbus, org.kde.kglobalaccel, /component/mediacontrol, invokeShortcut, playpausemedia] }
      CapsLock-Alt-w: { launch: [qdbus, org.kde.kglobalaccel, /component/mediacontrol, invokeShortcut, previousmedia] }
      CapsLock-Alt-e: { launch: [qdbus, org.kde.kglobalaccel, /component/mediacontrol, invokeShortcut, nextmedia] }
      CapsLock-Shift-s: { launch: [qdbus, org.kde.kglobalaccel, /component/mediacontrol, invokeShortcut, mediavolumedown] }
      CapsLock-Shift-d: { launch: [qdbus, org.kde.kglobalaccel, /component/mediacontrol, invokeShortcut, mediavolumeup] }

  - remap:
      CapsLock-t: tab
      CapsLock-Backspace: delete
      CapsLock-a: delete

      CapsLock-h: left
      CapsLock-j: down
      CapsLock-k: up
      CapsLock-l: right
      CapsLock-i: home
      CapsLock-o: end
      CapsLock-u: pageup
      CapsLock-p: pagedown

      CapsLock-s: ctrl-c
      CapsLock-w: ctrl-x
      CapsLock-d: ctrl-v
      CapsLock-f: ctrl-a