virtual_modifiers:
  - Tab
modmap:
  - remap:
      CapsLock: Esc
      Esc: Delete
      Compose: Super_R # For me, Compose is the Menu key
  - name: Game side mouse buttons fix
    remap:
      Btn_Side: k
      Btn_Extra: j
    application:
      only: /Terraria/
keymap:
  - name: Tile and focus input
    remap:
      Tab-b: ["super-8", "shift-tab", "shift-tab", "shift-tab", "shift-tab"] # banking on #8 toggling float
    application:
      only: Anki

  - remap:
      Shift-Esc: insert # because it's the kde compose key

  - remap:

      Tab-h: left
      Tab-j: down
      Tab-k: up
      Tab-l: right
      Tab-i: home
      Tab-o: end
      Tab-u: pageup
      Tab-p: pagedown

      Tab-LeftBrace: { launch: ["ydotool", "click", "c0"] } # c0 — left click
      Tab-RightBrace: { launch: ["ydotool", "click", "c1"] } # c1 — right click
      Tab-m: { launch: ["ydotool", "mousemove", "-w", "--", "-1", "0"] } # left
      Tab-Comma: { launch: ["ydotool", "mousemove", "-w", "--", "0", "1"] } # up
      Tab-Dot: { launch: ["ydotool", "mousemove", "-w", "--", "0", "-1"] } # down
      Tab-Slash: { launch: ["ydotool", "mousemove", "-w", "--", "1", "0"] } # up

      Tab-w: ctrl-insert
      Tab-e: shift-insert
      Tab-r: ctrl-a

      Super-Esc: { launch: ["xdotool", "getwindowfocus", "windowkill"] }
      # Show image in clipboard
      Super-w:
        {
          launch:
            [
              "bash",
              "-c",
              "xclip -selection clipboard -t image/png -o 2>/dev/null | display",
            ],
        }
