virtual_modifiers:
  - Tab
modmap:
  - remap:
      CapsLock: Esc
      Esc: Delete
    # application:
    #   only: terraria
keymap:
  - remap:
      Tab-t: Tab
      Tab-h: left
      Tab-j: down
      Tab-k: up
      Tab-l: right
      Tab-i: home
      Tab-o: end
      Tab-u: pageup
      Tab-p: pagedown

      Alt-Esc: { launch: ["xdotool", "getwindowfocus", "windowkill"] }
      Super-w:
        {
          launch:
            [
              "bash",
              "-c",
              "xclip -selection clipboard -t image/png -o 2>/dev/null | display",
            ],
        }
