vim.opt.number               = true
vim.opt.relativenumber       = true
vim.opt.tabstop              = 3
vim.opt.shiftwidth           = 3
vim.opt.expandtab            = false
vim.opt.smartindent          = true
vim.opt.mouse                = 'a'
vim.opt.ignorecase           = true
vim.opt.smartcase            = true
vim.opt.hlsearch             = true
vim.opt.colorcolumn          = ''
vim.opt.syntax               = 'enable'
vim.opt.termguicolors        = true
vim.opt.background           = 'dark'
vim.opt.backup               = false
vim.opt.writebackup          = false
vim.opt.swapfile             = false
vim.opt.undofile             = true
vim.opt.timeout              = false
vim.opt.eol                  = false
vim.opt.fixeol               = false
-- vim.opt.scrolloff            = 999
vim.g.mapleader              = ','
vim.g.rust_recommended_style = true
vim.o.cpoptions              = 'aABceFs'
vim.opt.splitbelow           = true
vim.opt.splitright           = true
vim.opt.virtualedit          = 'block'
vim.opt.inccommand           = 'split'
-- vim.opt.signcolumn           = 'no'
vim.diagnostic.config({ signs = false })
