Map("", "<C-d>", "6j")
Map("", "<C-u>", "6k")
Map("", ";", ":")
Map("", "'", '"')
Map("", ":", ",")
Map("", '"', ";")
Map("", "gm", "gM")
Map("", "<C-f>", "12jzz")
Map("", "<C-b>", "12kzz")
Map("", "<leader>a", "[m")
Map("", "<leader>s", "]m")
Map("", "<leader>A", "[M")
Map("", "<leader>S", "]M")

Map("v", "u", "<Esc>u")

Map("i", "<C-l>", "<C-x><C-l>")
Map("i", "<C-k>", "<C-o>O")
-- Map("i", "<C-j>", "<C-o>o")

Map("o", "{", "V{")
Map("o", "}", "V}")

Map("n", "<C-k>", "O<Esc>")
Map("n", "<C-j>", "o<Esc>")
Map("n", "&", "n&")
Map("n", "R", "q")
Map("n", "gK", "K")
Map("n", "X", "yl")
Map("n", "Y", "yg_")
Map("n", "~", "~h")
Map("n", "<Space>", "")
Map("n", "<BS>", "")
Map("n", "dp", "ddp")
Map("n", "dP", "ddkP")
Map("n", "yp", "yyp")
Map("n", "yP", "yyP")