abbr --set-cursor -a gmm   'git commit -m "%"'
abbr --set-cursor -a gamm  'git add . && git commit -am "%"'
abbr --set-cursor -a gammp 'git add . && git commit -am "%" && git push'
abbr --set-cursor -a tgg 'tgpt "%"'
abbr --set-cursor -a ytv 'yt-dlp -o \'%.%(ext)s\''
