std = 'neovim'

[rules]
unused_variable = 'allow'
global_usage = 'allow'
if_same_then_else = 'allow'
incorrect_standard_library_use = 'allow'
mixed_table = 'allow'
multiple_statements = 'allow'
undefined_variable = 'allow'
shadowing = 'allow'
empty_if = 'allow'
unscoped_variables = 'allow'
